# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_heading', models.CharField(blank=True, max_length=50)),
                ('feature_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqd_id', models.CharField(blank=True, max_length=10)),
                ('requirement_heading', models.CharField(blank=True, max_length=50)),
                ('requirement_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=10)),
                ('ticket_text', models.CharField(max_length=200)),
                ('release', models.CharField(max_length=5)),
                ('iteration', models.CharField(max_length=5)),
                ('is_feature', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joan.Feature')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joan.Requirement'),
        ),
    ]
