# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0002_auto_20170826_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='requirement',
        ),
        migrations.AddField(
            model_name='feature',
            name='requirement',
            field=models.ManyToManyField(to='joan.Requirement'),
        ),
    ]
