# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0003_auto_20170826_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_text',
            field=models.TextField(),
        ),
    ]
