# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0005_auto_20170826_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
