# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0006_ticket_ticket_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agmt_date_raised', models.DateTimeField(blank=True)),
                ('agmt_date_resolved', models.DateTimeField(blank=True)),
                ('agmt_issue', models.CharField(max_length=100)),
                ('agmt_issue_details', models.TextField(blank=True)),
                ('agmt_answer', models.CharField(max_length=100)),
                ('agmt_answer_details', models.TextField(blank=True)),
                ('agmt_resource_person', models.CharField(max_length=50)),
                ('agmt_medium', models.CharField(max_length=50)),
                ('is_external', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('requirement', models.ManyToManyField(to='joan.Requirement')),
            ],
            options={
                'ordering': ['agmt_date_raised', 'id', 'agmt_issue'],
            },
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['release', 'id', 'ticket_text']},
        ),
    ]
