# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0007_auto_20170826_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_company', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=50)),
                ('project_start_date', models.DateTimeField(blank=True)),
                ('project_end_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
