# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0008_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joan.Project'),
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joan.Project'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joan.Project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joan.Project'),
        ),
    ]
