# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0009_auto_20170826_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
