# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0010_auto_20170826_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='project',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_heading',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
