# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0011_auto_20170828_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(max_length=50)),
                ('release_target_date', models.DateField(blank=True, null=True)),
                ('release_actual_date', models.DateField(blank=True, null=True)),
                ('release_detais', models.CharField(blank=True, max_length=70)),
            ],
        ),
    ]
