# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0013_auto_20170828_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='release_detais',
            new_name='release_details',
        ),
    ]
