# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0015_auto_20170828_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
