# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0017_auto_20170828_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='reqd_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
