# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0018_auto_20170829_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_heading',
            field=models.CharField(blank=True, max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_text',
            field=models.CharField(max_length=200, verbose_name='Feature Name'),
        ),
    ]
