# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0019_auto_20170901_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature_description',
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_detail',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Details'),
        ),
    ]
