# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0021_auto_20170901_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joan.Release'),
        ),
    ]
