# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0022_feature_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='feature_detail',
            new_name='feature_details',
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_details',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='reqd_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_heading',
            field=models.CharField(blank=True, max_length=70, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_text',
            field=models.CharField(max_length=300, verbose_name='Requirement Name'),
        ),
    ]
