# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0023_auto_20170902_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joan.Project'),
        ),
    ]
