# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0024_requirement_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='release',
        ),
    ]
