# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0025_remove_requirement_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_uat_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='release_uat_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
