# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0026_auto_20170902_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='with_reqd_id',
            field=models.BooleanField(default=True, verbose_name='With Identifier'),
        ),
    ]
