# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0027_requirement_with_reqd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('NW', 'NEW'), ('IP', 'IN PROGRESS'), ('DO', 'DONE')], default='NW', max_length=2),
        ),
    ]
