# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0028_feature_feature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('NW', 'New'), ('IP', 'In Progress'), ('DO', 'Done')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='feature',
            name='requirement',
            field=models.ManyToManyField(related_name='requirements', to='joan.Requirement'),
        ),
    ]
