# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0029_auto_20170903_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='requirement',
            field=models.ManyToManyField(to='joan.Requirement'),
        ),
    ]
