# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0031_auto_20170903_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('label-default', 'New'), ('label-warning', 'Use Case Done'), ('label-info', 'In Progress'), ('label-done', 'Done')], default='label-default', max_length=2),
        ),
    ]
