# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0034_auto_20170903_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('NW', 'New'), ('DU', 'Use Case Done'), ('IP', 'In Progress'), ('DO', 'Done')], default='NW', max_length=2),
        ),
    ]
