# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0035_auto_20170903_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(blank=True, max_length=20)),
                ('sprint_details', models.CharField(blank=True, max_length=100, null=True)),
                ('sprint_start_date', models.DateField(blank=True, null=True)),
                ('sprint_end_date', models.DateField(blank=True, null=True)),
                ('feature_status', models.CharField(choices=[('NW', 'New'), ('AC', 'Active'), ('DO', 'Done')], default='NW', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joan.Project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joan.Release')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['sprint', 'id', 'ticket_text']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='release',
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('NW', 'New'), ('DU', 'UC Done'), ('IP', 'In Progress'), ('DO', 'Done')], default='NW', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joan.Sprint'),
        ),
    ]
