# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0036_auto_20170909_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='feature_status',
            new_name='sprint_status',
        ),
    ]
