# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0037_auto_20170909_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dev_assigned',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
