# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0038_ticket_dev_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('NW', 'New'), ('IP', 'In Progress'), ('FV', 'For FV'), ('DO', 'Done')], default='NW', max_length=2),
        ),
    ]
