# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0039_ticket_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='feature',
        ),
        migrations.AddField(
            model_name='ticket',
            name='feature',
            field=models.ManyToManyField(to='joan.Feature'),
        ),
    ]
