# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0040_auto_20170909_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='feature',
            new_name='features',
        ),
    ]
