# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0042_auto_20170910_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('NW', 'New'), ('DU', 'UC Done'), ('IP', 'In Progress'), ('FV', 'For FV'), ('DO', 'Done')], default='NW', max_length=2),
        ),
    ]
