# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0043_auto_20170917_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='feature_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='sprint_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_status',
            new_name='status',
        ),
    ]
