# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joan', '0044_auto_20170929_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
